/* 기술몬 18종. **도감이 곧 이력서입니다.**
   dex 문장은 전부 content/wiki.js 또는 content/journey.js에서 축약해 왔습니다.
   `wiki` 필드가 근거 조각을 가리킵니다 — 게임을 위해 수치를 지어내지 않습니다.
   근거가 없는 칸은 비워 두고, 비어 있다는 사실을 도감이 그대로 보여줍니다. */

/** 타입은 속성이 아니라 **개발 도메인**입니다. 상성표는 아래 EFFECT. */
export const TYPES = {
  FRONT: { name: '프론트', color: '#A8DDF0', ink: '#2E2A6B' },
  BACK: { name: '백엔드', color: '#7FA65C', ink: '#F4F1EA' },
  INFRA: { name: '인프라', color: '#E8A87C', ink: '#2E2A6B' },
  QUALITY: { name: '품질', color: '#F2C94C', ink: '#2E2A6B' },
  ARCH: { name: '구조', color: '#B8B0E8', ink: '#2E2A6B' },
  TEAM: { name: '팀', color: '#F5C6D0', ink: '#2E2A6B' },
};

/* 상성은 실제 개발의 인과를 옮긴 것입니다 —
   구조는 품질을 떠받치고, 품질은 인프라 사고를 줄이고, 팀은 구조를 정착시킵니다. */
export const EFFECT = {
  ARCH: { QUALITY: 2, TEAM: 0.5 },
  QUALITY: { INFRA: 2, ARCH: 0.5 },
  INFRA: { BACK: 2, QUALITY: 0.5 },
  BACK: { FRONT: 2, INFRA: 0.5 },
  FRONT: { TEAM: 2, BACK: 0.5 },
  TEAM: { ARCH: 2, FRONT: 0.5 },
};

export const MONS = [
  // ── 1번 회사 · 뉴비마을 ──────────────────────────────────────────
  {
    id: 'spring',
    no: 1,
    name: '스프링',
    en: 'Spring',
    type: 'BACK',
    where: 1,
    starter: false,
    dex: '첫 회사에서 받은 단 하나의 기술. "이것만 하면 된다"는 말과 함께 왔다. 시킨 만큼만 자란다.',
    flavor: '누구나 이걸로 시작하지만, 여기서 멈추면 여기까지가 전부다.',
    moves: ['의존성 주입', '트랜잭션', '컨트롤러', '야근'],
    base: { hp: 60, atk: 52, def: 58, spd: 45 },
    catchRate: 200,
    wiki: null,
  },
  {
    id: 'springboot',
    no: 2,
    name: '부트몬',
    en: 'Spring Boot',
    type: 'BACK',
    where: 1,
    dex: '퇴근하고 혼자 붙여 본 첫 기술. 시킨 사람이 없었다는 점에서 스프링과 다르다.',
    flavor: '허락을 기다리지 않은 첫 번째 증거.',
    moves: ['자동 설정', '내장 서버', '프로파일 분리', '혼자 배우기'],
    base: { hp: 68, atk: 60, def: 62, spd: 55 },
    catchRate: 150,
    wiki: 'modules',
  },
  {
    id: 'jpa',
    no: 3,
    name: '제이피에이',
    en: 'JPA',
    type: 'BACK',
    where: 1,
    dex: '객체와 테이블 사이를 오간다. 편해 보이지만 N+1을 부르는 습성이 있어, 나중에 검색 도메인에서 다시 만난다.',
    flavor: '편한 것에는 대개 청구서가 따라온다.',
    moves: ['영속성 컨텍스트', '지연 로딩', 'N+1', '페치 조인'],
    base: { hp: 64, atk: 55, def: 70, spd: 48 },
    catchRate: 150,
    wiki: 'search',
  },
  {
    id: 'react',
    no: 4,
    name: '리액트',
    en: 'React',
    type: 'FRONT',
    where: 1,
    dex: '화면이 없으면 아무도 쓰지 않는다는 걸 알고 건드린 기술. 백엔드만 하던 사람의 경계를 처음 넘게 했다.',
    flavor: '경계를 넘은 첫 걸음. 이 한 걸음이 나중에 풀스택이 된다.',
    moves: ['상태 관리', '리렌더', '컴포넌트 합성', '경계 넘기'],
    base: { hp: 66, atk: 63, def: 52, spd: 72 },
    catchRate: 150,
    wiki: 'front',
  },

  // ── 2번 회사 · 파도항구 ──────────────────────────────────────────
  {
    id: 'reactnative',
    no: 5,
    name: '알엔몬',
    en: 'React Native',
    type: 'FRONT',
    where: 2,
    dex: '두 번째 회사에서 처음 만졌다. 웹의 문법으로 앱을 만든다. 배운 것은 늘었지만, 배운 양이 실력 차를 메우지는 못했다.',
    flavor: '새 기술을 하나 더 아는 것과 잘하는 것은 다른 축이었다.',
    moves: ['네이티브 브리지', '플랫폼 분기', '핫 리로드', '따라잡기'],
    base: { hp: 70, atk: 66, def: 58, spd: 74 },
    catchRate: 120,
    wiki: null,
  },
  {
    id: 'aws',
    no: 6,
    name: '에이더블유에스',
    en: 'AWS',
    type: 'INFRA',
    where: 2,
    dex: '코드가 도는 곳이 누군가의 컴퓨터라는 걸 처음 실감하게 한 기술. 나중에 Elastic Beanstalk와 ALB 앞에서 다시 만난다.',
    flavor: '내 코드는 내 노트북 밖에서도 돌아야 한다.',
    moves: ['배포', '환경변수', '헬스체크', '요금 청구'],
    base: { hp: 78, atk: 60, def: 74, spd: 50 },
    catchRate: 110,
    wiki: 'ops',
  },

  // ── 3번 회사 · 공유마을 ──────────────────────────────────────────
  {
    id: 'insight',
    no: 7,
    name: '인사이트',
    en: 'Insight',
    type: 'TEAM',
    where: 3,
    dex: '기술이 아니다. 아는 것을 다 이해하기 전에 꺼내 놓는 습관이다. 세 번째 회사의 신입 동료들에게서 옮았다.',
    flavor: '혼자 잘하는 것이 성장인 줄 알았다. 아니었다.',
    moves: ['공유', '요약', '질문 던지기', '남의 실패담'],
    base: { hp: 82, atk: 58, def: 66, spd: 68 },
    catchRate: 90,
    wiki: 'team',
  },
  {
    id: 'ainews',
    no: 8,
    name: '뉴스몬',
    en: 'AI News',
    type: 'TEAM',
    where: 3,
    dex: '매일 새로 나오는 것을 먼저 읽고 팀에 던진다. 읽은 것을 도구로 바꾸는 습관은 네 번째 회사에서 에이전트 스킬 CLI가 된다.',
    flavor: '흘려보내면 뉴스, 도구로 만들면 자산.',
    moves: ['먼저 읽기', '팀 공유', '검증', '도구화'],
    base: { hp: 72, atk: 62, def: 58, spd: 86 },
    catchRate: 90,
    wiki: 'aiwork',
  },

  // ── 4번 회사 · ZIVO ─────────────────────────────────────────────
  {
    id: 'nextjs',
    no: 9,
    name: '넥스트',
    en: 'Next.js 16',
    type: 'FRONT',
    where: 4,
    dex: '해외 환자 대상이라 앱 설치 장벽 없이 검색 유입으로 도달해야 했다. 앱 우선 대신 웹을 선행했고, i18n은 쿠키가 아니라 URL 세그먼트 14개 언어를 택했다 — SEO 인덱싱과 CDN 캐시 적중 때문이다.',
    flavor: 'FRONT 저장소 1,947 커밋 중 대부분이 이 위에 쌓였다.',
    moves: ['App Router', '서버 컴포넌트', '14개 로케일', 'QR 주문·결제'],
    base: { hp: 84, atk: 78, def: 68, spd: 82 },
    catchRate: 60,
    wiki: 'front',
  },
  {
    id: 'fsd',
    no: 10,
    name: '에프에스디',
    en: 'FSD',
    type: 'ARCH',
    where: 4,
    dex: '계층이 단방향으로만 흐르게 강제하는 구조. 어드민 15명이 드나드는 저장소에서 공통 기반이 흔들리지 않게 했다. 위반은 refactor 커밋 349건으로 해소했다.',
    flavor: '좋은 구조는 문서가 아니라 도구가 지킨다.',
    moves: ['단방향 의존', '계층 분리', '경계 강제', '단계 이관'],
    base: { hp: 76, atk: 66, def: 92, spd: 58 },
    catchRate: 55,
    wiki: 'infra',
  },
  {
    id: 'playwright',
    no: 11,
    name: '플레이몬',
    en: 'Playwright',
    type: 'QUALITY',
    where: 4,
    dex: '결제 E2E를 의존성 0의 Node mock과 STOMP 스텁으로 자가검증했다. 하이드레이션 레이스로 생기던 플레이크는 sleep으로 덮지 않고 clickUntil/clickWhen으로 구조에서 없앴고, CI에서 --repeat-each=10 burn-in으로 정량 검출했다. 결과는 전 구간 플레이크 0.',
    flavor: 'sleep으로 덮은 테스트는 통과한 것이 아니라 미룬 것이다.',
    moves: ['burn-in ×10', 'clickUntil', 'STOMP 스텁', '플레이크 0'],
    base: { hp: 80, atk: 74, def: 80, spd: 70 },
    catchRate: 55,
    wiki: 'test',
  },
  {
    id: 'rbac',
    no: 12,
    name: '알백에이씨',
    en: 'RBAC Hybrid',
    type: 'ARCH',
    where: 4,
    dex: '권한 체크가 페이지마다 흩어지면 누락이 곧 데이터 유출이다. 전면 전환 대신 하이브리드를 택해 파트너는 level 기반을 유지하고 관리자/스태프만 menuCode+action 세분 모델을 적용했다. 분산된 체크는 usePermission 훅 하나로 모았다.',
    flavor: '버튼만 숨기는 것은 권한이 아니다.',
    moves: ['RBAC+GBAC+ABAC', 'usePermission', '감사 로그', '마이그레이션 V026'],
    base: { hp: 86, atk: 70, def: 94, spd: 52 },
    catchRate: 45,
    wiki: 'perm',
  },
  {
    id: 'opensearch',
    no: 13,
    name: '오픈서치',
    en: 'OpenSearch',
    type: 'BACK',
    where: 4,
    dex: '숙소 재고·요금이 외부 webhook으로 수시로 갱신되는데 변경마다 개별 재색인을 부르는 것이 병목이었다. Bulk API chunk 배치로 RTT를 chunk당 1회로 줄이고, hot path의 매칭 연산은 Snapshot에 미리 계산해 요청 경로에서 걷어냈다.',
    flavor: 'DB LIKE도 pgvector도 아닌 이유가 있었다 — 다국어 텍스트에 다중 필터 조합이라서.',
    moves: ['Bulk 재색인', 'Snapshot 선계산', 'N+1 제거', 'statement_timeout'],
    base: { hp: 88, atk: 86, def: 66, spd: 76 },
    catchRate: 45,
    wiki: 'search',
  },
  {
    id: 'resilience',
    no: 14,
    name: '리질리언스',
    en: 'Resilience4j',
    type: 'INFRA',
    where: 4,
    dex: '단일 LLM 프로바이더에 묶이면 장애 때 파이프라인 전체가 멈춘다. Gemini/Claude/OpenAI를 인터페이스로 추상화하고 CircuitBreaker를 43개 지점에 적용했다. 특정 LLM이 죽어도 파이프라인은 안 멈춘다.',
    flavor: '실패 비용이 큰 곳일수록 실패 경로를 먼저 설계한다.',
    moves: ['서킷브레이커', 'fallback 체인', '모델 티어', '헬스체크'],
    base: { hp: 90, atk: 78, def: 84, spd: 60 },
    catchRate: 40,
    wiki: 'ai',
  },
  {
    id: 'outbox',
    no: 15,
    name: '아웃박스',
    en: 'Outbox',
    type: 'ARCH',
    where: 4,
    dex: '돈과 직결되는 쿠폰 도메인. 트리거 발급을 동기 호출 대신 ShedLock 분산락 기반 Outbox 워커로 처리해 유실과 중복을 구조에서 막았다(멀티 인스턴스 안전). 백엔드 쿠폰 커밋 118건, 테스트 101건.',
    flavor: '성공 케이스는 누구나 만든다. 차이는 무너지는 방식에서 난다.',
    moves: ['ShedLock', '멱등 권위', 'consume/cancel 역연산', 'usage 파티셔닝'],
    base: { hp: 92, atk: 82, def: 90, spd: 54 },
    catchRate: 35,
    wiki: 'coupon',
  },
  {
    id: 'archunit',
    no: 16,
    name: '아크유닛',
    en: 'ArchUnit',
    type: 'QUALITY',
    where: 4,
    dex: 'Hexagonal 구조의 의존 방향을 CI에서 강제한다. 리뷰어의 기억력에 기대는 규칙은 규칙이 아니다 — 그래서 사람이 아니라 테스트를 게이트로 뒀다.',
    flavor: '규칙을 읽으라고 부탁하는 대신, 도구가 들고 다니게 했다.',
    moves: ['의존 방향 검사', 'CI 게이트', '레이어 규칙', '반례 탐색'],
    base: { hp: 78, atk: 72, def: 96, spd: 62 },
    catchRate: 40,
    wiki: 'coupon',
  },
  {
    id: 'vanilla',
    no: 17,
    name: '바닐라',
    en: 'vanilla-extract',
    type: 'FRONT',
    where: 4,
    dex: 'StyleX를 검토했으나 Next.js/Turbopack 호환성과 zero-runtime을 고려해 옮겨 갔다. 디자인 토큰 강제는 리뷰가 아니라 codemod 스크립트로 집행했다.',
    flavor: '검토했다가 안 쓴 것도 기록에 남긴다 — 왜 안 골랐는지가 근거다.',
    moves: ['zero-runtime', 'Sprinkles', '토큰 codemod', 'tokens:check'],
    base: { hp: 72, atk: 68, def: 64, spd: 84 },
    catchRate: 60,
    wiki: 'front',
  },
  {
    id: 'webgpu',
    no: 18,
    name: '웹지피유',
    en: 'WebGPU',
    type: 'INFRA',
    where: 4,
    dex: '이력서 사이트 자체를 만든 기술. 파티클 1만 6천 개를 컴퓨트 셰이더로 돌리고, 브라우저 안에서 소형 언어 모델을 굴려 질문이 서버로 나가지 않게 했다. 지금 이 게임의 타일과 스프라이트도 여기서 그려진다.',
    flavor: '이력서를 쓰는 대신 이력서를 만들었다.',
    moves: ['컴퓨트 셰이더', '인스턴싱', '온디바이스 LLM', '드로우콜 1회'],
    base: { hp: 74, atk: 88, def: 60, spd: 90 },
    catchRate: 50,
    wiki: 'site',
  },
];

/** 오프닝에서 고르는 첫 언어 3종. 어느 것을 골라도 서사는 같습니다 —
    1번 회사가 시킨 것은 Spring 하나였다는 것이 사실이기 때문입니다. */
export const STARTERS = [
  {
    id: 'java',
    name: '자바',
    type: 'BACK',
    mon: 'spring',
    line: '단단하지만 무겁다. 어디에나 있고, 그래서 어디서나 시킨다.',
  },
  {
    id: 'javascript',
    name: '자바스크립트',
    type: 'FRONT',
    mon: 'react',
    line: '가볍고 빠르지만 발밑이 자주 흔들린다. 화면에 가장 가깝다.',
  },
  {
    id: 'sql',
    name: '에스큐엘',
    type: 'ARCH',
    mon: 'jpa',
    line: '눈에 안 보이지만 전부 여기 쌓인다. 틀리면 제일 늦게 안다.',
  },
];

export const byId = Object.fromEntries(MONS.map((m) => [m.id, m]));
export const monsOf = (companyNo) => MONS.filter((m) => m.where === companyNo);
